### ISSUE TITLE
The result is 0.0?

### ISSUE THREAD

**Issue by alice-cool** [codexxxl/GraphVQA#10]
Dear scholar, I run the 70th epoch ,I found all "Test:" print log is always 0.0 . 

Generated Program (637):  computer monitor sitting on sitting on jumping sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on younger  Ground Truth Program (637): select ( ball )
Generated Program (638):  computer monitor sitting on sitting on jumping sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on younger  Ground Truth Program (638): exist ( [2] )
Generated Program (639):  computer monitor sitting on sitting on jumping sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on younger  Ground Truth Program (639): or ( [1], [3] )
Test: [  0/661] Time  4.763 ( 4.763)    Acc@Program   0.00 (  0.00)     Acc@ProgramGroup 0.00 (0.00)    Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short  94.50 ( 94.50)
Test: [ 50/661] Time  0.293 ( 0.383)    Acc@Program   0.00 (  0.00)     Acc@ProgramGroup 0.00 (0.00)    Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short  90.50 ( 93.85)
Test: [100/661] Time  0.294 ( 0.340)    Acc@Program   0.00 (  0.00)     Acc@ProgramGroup 0.00 (0.00)    Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short  95.50 ( 94.14)
Test: [150/661] Time  0.308 ( 0.325)    Acc@Program   0.00 (  0.00)     Acc@ProgramGroup 0.00 (0.00)    Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short  95.00 ( 93.98)
Test: [200/661] Time  0.300 ( 0.318)    Acc@Program   0.00 (  0.00)     Acc@ProgramGroup 0.00 (0.00)    Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short  92.50 ( 94.00)
Test: [250/661] Time  0.294 ( 0.313)    Acc@Program   0.00 (  0.00)     Acc@ProgramGroup 0.00 (0.00)    Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short  96.00 ( 94.00)
Test: [300/661] Time  0.298 ( 0.310)    Acc@Program   0.00 (  0.00)     Acc@ProgramGroup 0.00 (0.00)    Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short  95.50 ( 94.01)
Test: [350/661] Time  0.298 ( 0.308)    Acc@Program   0.00 (  0.00)     Acc@ProgramGroup 0.00 (0.00)    Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short  94.00 ( 93.99)
Test: [400/661] Time  0.299 ( 0.307)    Acc@Program   0.00 (  0.00)     Acc@ProgramGroup 0.00 (0.00)    Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short  94.00 ( 93.98)
Test: [450/661] Time  0.286 ( 0.305)    Acc@Program   0.00 (  0.00)     Acc@ProgramGroup 0.00 (0.00)    Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short  95.00 ( 93.96)
Test: [500/661] Time  0.299 ( 0.304)    Acc@Program   0.00 (  0.00)     Acc@ProgramGroup 0.00 (0.00)    Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short  95.00 ( 93.96)
Test: [550/661] Time  0.293 ( 0.304)    Acc@Program   0.00 (  0.00)     Acc@ProgramGroup 0.00 (0.00)    Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short  94.00 ( 93.92)
Test: [600/661] Time  0.293 ( 0.303)    Acc@Program   0.00 (  0.00)     Acc@ProgramGroup 0.00 (0.00)    Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short  94.50 ( 93.92)
Test: [650/661] Time  0.296 ( 0.302)    Acc@Program   0.00 (  0.00)     Acc@ProgramGroup 0.00 (0.00)    Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short  97.50 ( 93.96)
Test: [660/661] Time  0.098 ( 0.302)    Acc@Program   0.00 (  0.00)     Acc@ProgramGroup 0.00 (0.00)    Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short  96.77 ( 93.95)
Test: [661/661] Time  0.098 ( 0.302)    Acc@Program   0.00 (  0.00)     Acc@ProgramGroup 0.00 (0.00)    Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short  96.77 ( 93.95)
Epoch: [70][   0/4715]  Time 4.50 (4.50)        Data 4.12 (4.12)        Loss 1.02e-01 (1.02e-01)        Acc@Program 0.00 (0.00) Acc@ProgramGroup 0.00 (0.00)    Acc@ProgramNonEmpty

**Comment by alice-cool** [comment]
(pytorch) byd@sbz:~/GraphVQA$ CUDA_VISIBLE_DEVICES=0 python mainExplain_gat.py --log-name debug.log --batch-size=200 --lr_drop=90
Not using distributed mode
git:
  sha: 16da6a024a2e8d050ad9f957449ff0670e9dc804, status: has uncommited changes, branch: master

Namespace(data='./', save_dir='./', log_name='debug.log', workers=32, epochs=300, start_epoch=0, batch_size=200, lr=0.0001, lr_drop=90, momentum=0.9, weight_decay=0.0001, print_fr eq=50, resume='', evaluate=False, evaluate_sets=['val_unbiased'], seed=None, output_dir='./outputdir', world_size=1, dist_url='env://', distributed=False)
finished loading the data, totally 943000 instances
finished loading the data, totally 132062 instances
number of params: 66989555
Epoch: [0][   0/4715]   Time 7.26 (7.26)

**Comment by alice-cool** [comment]
Epoch: [199][3700/4715] Time 0.19 (0.24)        Data 0.00 (0.03)        Loss 1.30e-02 (1.34e-02)        Acc@Program 0.00 (0.00) Acc@ProgramGroup 0.00 (0.00)    Acc@ProgramNonEmpty 0.00 (0.00)     Acc@Short 99.50 (99.49)
Traceback (most recent call last):
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 990, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/queues.py", line 113, in get
    if not self._poll(timeout):
  File "/home/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/connection.py", line 262, in poll
    return self._poll(timeout)
  File "/home/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/connection.py", line 429, in _poll
    r = wait([self], timeout)
  File "/home/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/connection.py", line 936, in wait
    ready = selector.select(timeout)
  File "/home/anaconda3/envs/pytorch/lib/python3.9/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 24878) is killed by signal: Killed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/byd/GraphVQA/mainExplain_gat.py", line 1055, in <module>
    main(args)
  File "/home/byd/GraphVQA/mainExplain_gat.py", line 357, in main
    train(train_loader, model, criterion, optimizer, epoch, args)
  File "/home/byd/GraphVQA/mainExplain_gat.py", line 418, in train
    for i, (data_batch) in enumerate(train_loader):
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1186, in _next_data
    idx, data = self._get_data()
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1152, in _get_data
    success, data = self._try_get_data()
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1003, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 24878) exited unexpectedly
