### ISSUE TITLE
preprocess.py output? 

### ISSUE THREAD

**Issue by alice-cool** [codexxxl/GraphVQA#9]
Dear scholar, I want to know if the following output result is right when I run the script" python preprocess.py"

(pytorch) byd@sbz:~/GraphVQA$ python preprocess.py
False
total 12578 programs
Neural Execution Engine Annotations: empty_buffer_counter 0 multi_buffer_counter 0 total_buffer_counter 0 multi_2_buffer_count 0 max_full_anwer_len 0 max_instr_len 0 max_new_programs_decoder_len 58
finished 12578/0
total 132062 programs
EXE Buffer Referring Empty Object! sg_obj_id_list [522188] imageId 2385163 question Who is wearing jeans?
Ptr Annotations Referring Empty Object! annotations {'answer': {'0': '522167'}, 'question': {'3': '522188'}, 'fullAnswer': {'1': '522167', '4': '522188'}} imageId 2385163 question Who is wearing jeans?
Ptr Annotations Referring Empty Object! annotations {'answer': {'0': '522167'}, 'question': {'3': '522188'}, 'fullAnswer': {'1': '522167', '4': '522188'}} imageId 2385163 question Who is wearing jeans?
EXE Buffer Referring Empty Object! sg_obj_id_list [598411] imageId 2371329 question What is on the brick building?
EXE Buffer Referring Empty Object! sg_obj_id_list [598411] imageId 2371329 question What is on the brick building?
Ptr Annotations Referring Empty Object! annotations {'answer': {'0': '598407'}, 'question': {'4:6': '598411'}, 'fullAnswer': {'1': '598407', '5': '598411'}} imageId 2371329 question What is on the brick building?
Ptr Annotations Referring Empty Object! annotations {'answer': {'0': '598407'}, 'question': {'4:6': '598411'}, 'fullAnswer': {'1': '598407', '5': '598411'}} imageId 2371329 question What is on the brick building?
Neural Execution Engine Annotations: empty_buffer_counter 51407 multi_buffer_counter 10325 total_buffer_counter 413705 multi_2_buffer_count 10177 max_full_anwer_len 15 max_instr_len 10 max_new_programs_decoder_len 58
finished 132062/0
total 943000 programs
EXE Buffer Referring Empty Object! sg_obj_id_list [1293422] imageId 2385742 question Is the box to the left or to the right of the standing person on the sidewalk?
Ptr Annotations Referring Empty Object! annotations {'answer': {}, 'question': {'2': '1293429', '12:14': '1293421', '16': '1293422'}, 'fullAnswer': {'1': '1293429', '8': '1293421'}} imageId 2385742 question Is the box to the left or to the right of the standing person on the sidewalk?
EXE Buffer Referring Empty Object! sg_obj_id_list [267528] imageId 2408131 question Is the green tree behind or in front of the building the fruits are in front of?
Ptr Annotations Referring Empty Object! annotations {'answer': {}, 'question': {'10': '267514', '12': '267528', '2:4': '267508'}, 'fullAnswer': {'1': '267508', '5': '267514'}} imageId 2408131 question Is the green tree behind or in front of the building the fruits are in front of?
EXE Buffer Referring Empty Object! sg_obj_id_list [152851] imageId 2414741 question The man that is to the left of the train is wearing what?
EXE Buffer Referring Empty Object! sg_obj_id_list [152851] imageId 2414741 question The man that is to the left of the train is wearing what?
Ptr Annotations Referring Empty Object! annotations {'answer': {'0': '152851'}, 'question': {'1': '152844', '9': '152849'}, 'fullAnswer': {'1': '152844', '4': '152851'}} imageId 2414741 question The man that is to the left of the train is wearing what?
Ptr Annotations Referring Empty Object! annotations {'answer': {'0': '152851'}, 'question': {'1': '152844', '9': '152849'}, 'fullAnswer': {'1': '152844', '4': '152851'}} imageId 2414741 question The man that is to the left of the train is wearing what?
EXE Buffer Referring Empty Object! sg_obj_id_list [1749668] imageId 2355048 question The backpack is on what?
EXE Buffer Referring Empty Object! sg_obj_id_list [1749668] imageId 2355048 question The backpack is on what?
Ptr Annotations Referring Empty Object! annotations {'answer': {'0': '1749668'}, 'question': {'1': '2061958'}, 'fullAnswer': {'1': '2061958', '5': '1749668'}} imageId 2355048 question The backpack is on what?
Ptr Annotations Referring Empty Object! annotations {'answer': {'0': '1749668'}, 'question': {'1': '2061958'}, 'fullAnswer': {'1': '2061958', '5': '1749668'}} imageId 2355048 question The backpack is on what?
EXE Buffer Referring Empty Object! sg_obj_id_list [1749668] imageId 2355048 question What's on the table?
Ptr Annotations Referring Empty Object! annotations {'answer': {'0': '2061958'}, 'question': {}, 'fullAnswer': {'1': '2061958', '5': '1749668'}} imageId 2355048 question What's on the table?
EXE Buffer Referring Empty Object! sg_obj_id_list [267528] imageId 2408131 question Is the green tree in front of the building that is behind the fruits?
Ptr Annotations Referring Empty Object! annotations {'answer': {}, 'question': {'8': '267514', '13': '267528', '2:4': '267508'}, 'fullAnswer': {'2': '267508', '6': '267514'}} imageId 2408131 question Is the green tree in front of the building that is behind the fruits?
Neural Execution Engine Annotations: empty_buffer_counter 368088 multi_buffer_counter 72233 total_buffer_counter 2952194 multi_2_buffer_count 71053 max_full_anwer_len 16 max_instr_len 10 max_new_programs_decoder_len 58
finished 943000/0

**Comment by alice-cool** [comment]
Dear scholar,
 when I run by some epochs, abruptly encounter the following bugs?


Epoch: [4][3250/4715]   Time 0.18 (0.18)        Data 0.00 (0.01)        Loss 4.74e-01 (5.42e-01)        Acc@Program 0.00 (0.00) Acc@ProgramGroup 0.00 (0.00)    Acc@ProgramNonEmpty 0.00 (0.00)     Acc@Short 78.50 (77.68)
Traceback (most recent call last):
  File "/home/byd/GraphVQA/mainExplain_gat.py", line 1055, in <module>
    main(args)
  File "/home/byd/GraphVQA/mainExplain_gat.py", line 357, in main
    train(train_loader, model, criterion, optimizer, epoch, args)
  File "/home/byd/GraphVQA/mainExplain_gat.py", line 418, in train
    for i, (data_batch) in enumerate(train_loader):
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1186, in _next_data
    idx, data = self._get_data()
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1152, in _get_data
    success, data = self._try_get_data()
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 990, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 289, in rebuild_storage_fd
    fd = df.detach()
  File "/home/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/home/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/reduction.py", line 189, in recv_handle
    return recvfds(s, 1)[0]
  File "/home/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/reduction.py", line 164, in recvfds
    raise RuntimeError('received %d items of ancdata' %
RuntimeError: received 0 items of ancdata

**Comment by alice-cool** [comment]
torch.multiprocessing.set_sharing_strategy('file_system')
